### ISSUE TITLE
 make build error:

### ISSUE THREAD

**Issue by ives9638** [bnclabs/xorfilter#18]
Caused by:
  failed to parse manifest at `~/cbordata-derive-0.5.3/Cargo.toml`

Caused by:
  feature `edition2021` is required

  The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.56.0-nightly (cc17afbb0 2021-08-02)).
  Consider trying a more recent nightly release.

**Comment by prataprc** [comment]
Sorry, my bad. I have tried to fix it in the latest version 77755a92. Hope it works. Thanks,

**Comment by ives9638** [comment]
Thanks  your reply. 
Serialize / Deserialize Xor8 type. Do you have a release time  for the feature

**Comment by prataprc** [comment]
#1 tracks that issue. Already some flavor of serialize is available. I have also laid out, on the issue description, the challenges in serializing xorfilters. Meanwhile the latest git tip contains a serialization implementation based on CBOR format. A of now I prefer to take that route. If you have more comments or need clarifications please post it under #1. Meanwhile if this issue is resolved, let us know, we can close this one.
